export const {
  AIRBNB_API_KEY,
  AIRBNB_TOKEN,
  AIRBNB_PASSWORD,
  AIRBNB_USERNAME,
  AUGUST_USERNAME,
  AUGUST_PASSWORD,
  PUSHOVER_USER,
  AIRBNB_PUSHOVER_TOKEN,
  DEBUG = "false",
} = process.env;
